### ISSUE TITLE
Impl

### ISSUE THREAD

**Issue by g4s8** [g4s8/ghman#1]
GhMan is a GitHub Telegram bot manager which helps to process notifications and configure notification rules.
Let's specify requirements in the readme and implement a prototype.

**Comment by g4s8** [comment]
done

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#1` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@g4s8 10 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#3](https://github.com/g4s8/ghman/issues/3), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#6](https://github.com/g4s8/ghman/issues/6), [#8](https://github.com/g4s8/ghman/issues/8) are still not solved; solved: [#7](https://github.com/g4s8/ghman/issues/7).

**Comment by 0pdd** [comment]
@g4s8 9 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#3](https://github.com/g4s8/ghman/issues/3), [#4](https://github.com/g4s8/ghman/issues/4), [#6](https://github.com/g4s8/ghman/issues/6), [#8](https://github.com/g4s8/ghman/issues/8) are still not solved; solved: [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7).

**Comment by 0pdd** [comment]
@g4s8 17 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#6](https://github.com/g4s8/ghman/issues/6), [#8](https://github.com/g4s8/ghman/issues/8) are still not solved; solved: [#2](https://github.com/g4s8/ghman/issues/2), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7).

**Comment by 0pdd** [comment]
@g4s8 17 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#2](https://github.com/g4s8/ghman/issues/2), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 17 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#2](https://github.com/g4s8/ghman/issues/2), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 16 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#19](https://github.com/g4s8/ghman/issues/19), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 15 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 14 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#40](https://github.com/g4s8/ghman/issues/40), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 14 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#3](https://github.com/g4s8/ghman/issues/3), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 13 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#3](https://github.com/g4s8/ghman/issues/3), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 12 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#3](https://github.com/g4s8/ghman/issues/3), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 11 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#3](https://github.com/g4s8/ghman/issues/3), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 11 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#3](https://github.com/g4s8/ghman/issues/3), [#42](https://github.com/g4s8/ghman/issues/42), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6), [#75](https://github.com/g4s8/ghman/issues/75) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#43](https://github.com/g4s8/ghman/issues/43), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 13 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#36](https://github.com/g4s8/ghman/issues/36), [#3](https://github.com/g4s8/ghman/issues/3), [#42](https://github.com/g4s8/ghman/issues/42), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6), [#75](https://github.com/g4s8/ghman/issues/75), [#82](https://github.com/g4s8/ghman/issues/82), [#83](https://github.com/g4s8/ghman/issues/83), [#84](https://github.com/g4s8/ghman/issues/84) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#35](https://github.com/g4s8/ghman/issues/35), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#43](https://github.com/g4s8/ghman/issues/43), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 12 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#36](https://github.com/g4s8/ghman/issues/36), [#3](https://github.com/g4s8/ghman/issues/3), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6), [#75](https://github.com/g4s8/ghman/issues/75), [#82](https://github.com/g4s8/ghman/issues/82), [#83](https://github.com/g4s8/ghman/issues/83), [#84](https://github.com/g4s8/ghman/issues/84) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#35](https://github.com/g4s8/ghman/issues/35), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).

**Comment by 0pdd** [comment]
@g4s8 11 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#34](https://github.com/g4s8/ghman/issues/34), [#3](https://github.com/g4s8/ghman/issues/3), [#44](https://github.com/g4s8/ghman/issues/44), [#53](https://github.com/g4s8/ghman/issues/53), [#62](https://github.com/g4s8/ghman/issues/62), [#6](https://github.com/g4s8/ghman/issues/6), [#75](https://github.com/g4s8/ghman/issues/75), [#82](https://github.com/g4s8/ghman/issues/82), [#83](https://github.com/g4s8/ghman/issues/83), [#84](https://github.com/g4s8/ghman/issues/84) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#2](https://github.com/g4s8/ghman/issues/2), [#35](https://github.com/g4s8/ghman/issues/35), [#36](https://github.com/g4s8/ghman/issues/36), [#37](https://github.com/g4s8/ghman/issues/37), [#38](https://github.com/g4s8/ghman/issues/38), [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#4](https://github.com/g4s8/ghman/issues/4), [#5](https://github.com/g4s8/ghman/issues/5), [#7](https://github.com/g4s8/ghman/issues/7), [#8](https://github.com/g4s8/ghman/issues/8).
