### ISSUE TITLE
It's not possible to close issue

### ISSUE THREAD

**Issue by g4s8** [g4s8/ghman#11]
User should be able to close issue by clicking inline button if he's an author of issue or has permissions to do that.

**Comment by 0crat** [comment]
Job [#11](https://github.com/g4s8/ghman/issues/11) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#11](https://github.com/g4s8/ghman/issues/11); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by g4s8** [comment]
@0crat assign @olenagerasimova

**Comment by 0crat** [comment]
> @0crat assign @olenagerasimova ([here](https://github.com/g4s8/ghman/issues/11#issuecomment-498257294))

@g4s8 The job [#11](https://github.com/g4s8/ghman/issues/11) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/d8749307-591a-4537-865e-36435afc80a5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@0crat wait please, I need more time

**Comment by 0crat** [comment]
> @0crat wait please, I need more time ([here](https://github.com/g4s8/ghman/issues/11#issuecomment-501245848))

@olenagerasimova The impediment for [#11](https://github.com/g4s8/ghman/issues/11) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by olenagerasimova** [comment]
@g4s8 could you please give me a hint how to find out whether user has permission close the issue? As far as I understand in public repos owners can close any issue, but what about private repos?

**Comment by g4s8** [comment]
@olenagerasimova let's start with simple check that current user is issue author, authors can close self issues.

**Comment by olenagerasimova** [comment]
@g4s8 can't get how to check this, we do not have github user id. I can get issue author from `Issue.Smart` instance, but I do not see how to check whether this author is our user. Should we add github id to `user` table or am I missing something?

**Comment by g4s8** [comment]
@olenagerasimova you can add a method to `GhUser` class to get current user, e.g.:
```java
public User user() {
    return this.ghb.users().self();
}
```
`Github` object will find current user by OAuth token and return it in `self()` method.

**Comment by olenagerasimova** [comment]
@g4s8 thanks

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#54](https://github.com/g4s8/ghman/issues/54), [#55](https://github.com/g4s8/ghman/issues/55) are still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 #46 was merged, could you please close this issue?

**Comment by g4s8** [comment]
@olenagerasimova thanks

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#11](https://github.com/g4s8/ghman/issues/11) is not in the agenda of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), can't inspect

**Comment by 0crat** [comment]
The job [#11](https://github.com/g4s8/ghman/issues/11) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#54](https://github.com/g4s8/ghman/issues/54) is still not solved; solved: [#55](https://github.com/g4s8/ghman/issues/55).
