### ISSUE TITLE
Windows: lines in file should end with Unix-like end of line

### ISSUE THREAD

**Issue by olenagerasimova** [g4s8/ghman#14]
Trying to run qulice check on windows I'm getting multiple complaints 
```
Checkstyle: D:\EO\ghman\src\main\java\com\g4s8\ghman\web\WebApp.java[39]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
```
Please, modify .`gitattributes` file for Unix-like end of line

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#14](https://github.com/g4s8/ghman/issues/14) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
The job [#14](https://github.com/g4s8/ghman/issues/14) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/449ac5d4-87de-4537-847a-007061d8a6c5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/g4s8/ghman/issues/14#issuecomment-500116350))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#14](https://github.com/g4s8/ghman/issues/14), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#14](https://github.com/g4s8/ghman/issues/14) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/2f658d76-99bf-49ab-8e53-fd3eba797e00); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat waiting for merge of #24

**Comment by 0crat** [comment]
> @0crat waiting for merge of #24  ([here](https://github.com/g4s8/ghman/issues/14#issuecomment-500480590))

@scristalli The impediment for [#14](https://github.com/g4s8/ghman/issues/14) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by scristalli** [comment]
@olenagerasimova #24 has been merged, I think the issue is fixed. Could you please confirm and close?

**Comment by olenagerasimova** [comment]
@scristalli thanks, do not have my windows computer around right now, will check in several hours

**Comment by olenagerasimova** [comment]
@scristalli all good, thanks

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#14](https://github.com/g4s8/ghman/issues/14) is not in the agenda of @scristalli[/z](https://www.0crat.com/u/scristalli), can't inspect

**Comment by 0crat** [comment]
The job [#14](https://github.com/g4s8/ghman/issues/14) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)
