### ISSUE TITLE
PgUsers.java:105-108: Replace this static method with an...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#18]
The puzzle `7-2fb4e7d6` from #7 has to be resolved: 

https://github.com/g4s8/ghman/blob/0b2f63b3f8b0108f2f156c34d4e962f557082b46/src/main/java/com/g4s8/ghman/data/PgUsers.java#L105-L108

The puzzle was created by @rultor on 07-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#18](https://github.com/g4s8/ghman/issues/18) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#18](https://github.com/g4s8/ghman/issues/18) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/cc9b2116-61ac-4630-81d5-ce6a6ba18398); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #32 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #32 to be merged ([here](https://github.com/g4s8/ghman/issues/18#issuecomment-502436479))

@victornoel The impediment for [#18](https://github.com/g4s8/ghman/issues/18) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `7-2fb4e7d6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#53](https://github.com/g4s8/ghman/issues/53) is still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#18](https://github.com/g4s8/ghman/issues/18) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
The job [#18](https://github.com/g4s8/ghman/issues/18) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
