### ISSUE TITLE
Usage of deprecated class UncheckedScalar

### ISSUE THREAD

**Issue by scristalli** [g4s8/ghman#25]
`UncheckedScalar` has been deprecated in cactoos. Its usage should be removed from code.
The new `Unchecked` class should be used instead.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@scristalli what is an alternative? What class should we use for scalars with unchecked exceptions?

**Comment by scristalli** [comment]
@g4s8 the alternative is `Unchecked`, as specified in the [deprecated class](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/scalar/UncheckedScalar.java#L33)
I updated the task description.

**Comment by 0crat** [comment]
Job [#25](https://github.com/g4s8/ghman/issues/25) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
The job [#25](https://github.com/g4s8/ghman/issues/25) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/02cbb184-726c-4e67-99fe-12d0d5c758f6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat wait for #50 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #50 to be merged ([here](https://github.com/g4s8/ghman/issues/25#issuecomment-504672791))

@victornoel The impediment for [#25](https://github.com/g4s8/ghman/issues/25) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@scristalli the PR has been merged, you can close this issue I believe :)

**Comment by 0crat** [comment]
Job [#25](https://github.com/g4s8/ghman/issues/25) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#25](https://github.com/g4s8/ghman/issues/25) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
