### ISSUE TITLE
Use DBUnit for Database Unit tests

### ISSUE THREAD

**Issue by samihibrahim** [g4s8/ghman#28]
Related to Issue #20, the status now is we are using JUnit 5 Extensions for database initialization and tear-down. I believe using a db mock (e.g. DBUnit) will provide a better alternative. Should I start the implementation or do you prefer the current setup?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@samihibrahim as I understood correctly, DBUnit is a database mock, right? If yes, it may be suitable for unit testing, but I think integration tests with real database are more important on early stage, but we can start using DBUnit tests later, when we have more stable code.

**Comment by samihibrahim** [comment]
@g4s8 fair enough.

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#28` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
