### ISSUE TITLE
Notification.java:43-48: Continue implement notifications...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#29]
The puzzle `9-ed24d84f` from #9 has to be resolved: 

https://github.com/g4s8/ghman/blob/e8bd4097c1ef60b9fcb11631384a41e56bb02c7d/src/main/java/com/g4s8/ghman/bot/Notification.java#L43-L48

The puzzle was created by @rultor on 15-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#29](https://github.com/g4s8/ghman/issues/29) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#29](https://github.com/g4s8/ghman/issues/29) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/8e906aef-62ac-4c3c-8c89-ced6cc14b199); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@g4s8 to solve this, I plan to run `Notification.UnreadThreads.send()` inside `TkSync` but this means that the `WebApp` must know about the `BotSimple` object (so that it can be passed up to `UnreadThreads` constructor).

The problem is that the `BotSimple` object is constructed inside `BotApp` so is not available from within `App` where `WebApp` is constructed.

Do you:
- think this is the correct approach architecturally speaking, i.e. the `WebApp` and the `BotApp` manipulating the same `BotSimple` object, or should I instantiate another `BotSimple` just for `WebApp`?
- have an idea about the best way to handle this and where should the `BotSimple` be constructed then? Inside `App`?

**Comment by victornoel** [comment]
@0crat waiting for ARC answer

**Comment by 0crat** [comment]
> @0crat waiting for ARC answer ([here](https://github.com/g4s8/ghman/issues/29#issuecomment-508943835))

@victornoel The impediment for [#29](https://github.com/g4s8/ghman/issues/29) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@g4s8 ping

**Comment by victornoel** [comment]
@g4s8 forget about it, I made a PR with a solution that seemed good enough.

**Comment by victornoel** [comment]
@0crat wait for #66 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #66 to be merged ([here](https://github.com/g4s8/ghman/issues/29#issuecomment-511192448))

@victornoel Job [#29](https://github.com/g4s8/ghman/issues/29) is already on hold

**Comment by 0pdd** [comment]
The puzzle `9-ed24d84f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#73](https://github.com/g4s8/ghman/issues/73) is still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#29](https://github.com/g4s8/ghman/issues/29) is now out of scope

**Comment by 0crat** [comment]
Job [#29](https://github.com/g4s8/ghman/issues/29) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
