### ISSUE TITLE
TkApp.java:54-57: Refactor this class: extract additional...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#4]
The puzzle `1-ba24450c` from #1 has to be resolved: 

https://github.com/g4s8/ghman/blob/a8f587ea02446832a0de164a20b03d7667218015/src/main/java/com/g4s8/ghman/web/TkApp.java#L54-L57

The puzzle was created by @g4s8 on 22-May-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#4](https://github.com/g4s8/ghman/issues/4) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#4](https://github.com/g4s8/ghman/issues/4); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#4](https://github.com/g4s8/ghman/issues/4) assigned to @samihibrahim[/z](https://www.0crat.com/u/samihibrahim), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/2bf0363c-0cfb-45d7-97ac-a995b0acb7dc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#4` already assigned to @samihibrahim, can't assign to @samihibrahim

**Comment by samihibrahim** [comment]
@0crat wait while PR #13 is merged

**Comment by 0crat** [comment]
> @0crat wait while PR #13 is merged ([here](https://github.com/g4s8/ghman/issues/4#issuecomment-499068334))

@samihibrahim The impediment for [#4](https://github.com/g4s8/ghman/issues/4) was registered successfully by @samihibrahim[/z](https://www.0crat.com/u/samihibrahim)

**Comment by 0pdd** [comment]
The puzzle `1-ba24450c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43) are still not solved.

**Comment by 0crat** [comment]
Job [#4](https://github.com/g4s8/ghman/issues/4) is not in the agenda of @samihibrahim[/z](https://www.0crat.com/u/samihibrahim), can't inspect

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @samihibrahim[/z](https://www.0crat.com/u/samihibrahim), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#4](https://github.com/g4s8/ghman/issues/4) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @samihibrahim[/z](https://www.0crat.com/u/samihibrahim)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#39](https://github.com/g4s8/ghman/issues/39), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43) are still not solved; solved: [#40](https://github.com/g4s8/ghman/issues/40).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#39](https://github.com/g4s8/ghman/issues/39), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#62](https://github.com/g4s8/ghman/issues/62) are still not solved; solved: [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43), [#62](https://github.com/g4s8/ghman/issues/62) are still not solved; solved: [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#42](https://github.com/g4s8/ghman/issues/42), [#62](https://github.com/g4s8/ghman/issues/62), [#75](https://github.com/g4s8/ghman/issues/75) are still not solved; solved: [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#43](https://github.com/g4s8/ghman/issues/43).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#62](https://github.com/g4s8/ghman/issues/62), [#75](https://github.com/g4s8/ghman/issues/75) are still not solved; solved: [#39](https://github.com/g4s8/ghman/issues/39), [#40](https://github.com/g4s8/ghman/issues/40), [#41](https://github.com/g4s8/ghman/issues/41), [#42](https://github.com/g4s8/ghman/issues/42), [#43](https://github.com/g4s8/ghman/issues/43).
