### ISSUE TITLE
FkGitHubAuthRedirection.java:33-34: Replace the call to...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#40]
The puzzle `4-ff388267` from #4 has to be resolved: 

https://github.com/g4s8/ghman/blob/2198cd8faa8fac8cd00a046d4cf4f2f9dd06763e/src/main/java/com/g4s8/ghman/web/FkGitHubAuthRedirection.java#L33-L34

The puzzle was created by Samih Omer on 08-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#40](https://github.com/g4s8/ghman/issues/40) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#40](https://github.com/g4s8/ghman/issues/40) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/abfae941-70db-43fc-97b9-336c216b9c4c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@g4s8 I noticed that `FormattedText` is much better after recent modifications in Cactoos. Now `asString()` throws `IOException` instead of `Exception`, and an unchecked `toString()` is available.
Since we know this, it would be pointless not to use this improved version from the start, so I'm going to request a release.

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by scristalli** [comment]
@0crat waiting for a release of cactoos to use the new `FormattedText` functionalities, see [here](https://github.com/yegor256/cactoos/pull/1131#issuecomment-507211946).

**Comment by 0crat** [comment]
> @0crat waiting for a release of cactoos to use the new `FormattedText` functionalities, see [here... ([here](https://github.com/g4s8/ghman/issues/40#issuecomment-507212399))

@scristalli The impediment for [#40](https://github.com/g4s8/ghman/issues/40) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0pdd** [comment]
The puzzle `4-ff388267` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#40](https://github.com/g4s8/ghman/issues/40) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
