### ISSUE TITLE
FkGitHubAuthRedirection.java:35-36: Implement unit tests...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#41]
The puzzle `4-05012186` from #4 has to be resolved: 

https://github.com/g4s8/ghman/blob/2198cd8faa8fac8cd00a046d4cf4f2f9dd06763e/src/main/java/com/g4s8/ghman/web/FkGitHubAuthRedirection.java#L35-L36

The puzzle was created by Samih Omer on 16-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#41](https://github.com/g4s8/ghman/issues/41) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#41](https://github.com/g4s8/ghman/issues/41) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/770ab633-53ed-4252-b2f6-fde1c60e13d5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@0crat wait for PR #56 review/merge

**Comment by 0crat** [comment]
> @0crat wait for PR #56 review/merge ([here](https://github.com/g4s8/ghman/issues/41#issuecomment-508520658))

@olenagerasimova The impediment for [#41](https://github.com/g4s8/ghman/issues/41) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
The puzzle `4-05012186` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#62](https://github.com/g4s8/ghman/issues/62) is still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#41](https://github.com/g4s8/ghman/issues/41) is now out of scope

**Comment by ammaratef45** [comment]
@olenagerasimova All commit messages should start with the mention of the issue

One of your commit messages doesn't start with the mention of the issue

Please confirm you will try to avoid that in the future

**Comment by olenagerasimova** [comment]
@ammaratef45 I confirm

**Comment by ammaratef45** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
