### ISSUE TITLE
TkGitHubAuthorization.java:36-38: replace those static...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#42]
The puzzle `4-c1ef585e` from #4 has to be resolved: 

https://github.com/g4s8/ghman/blob/2198cd8faa8fac8cd00a046d4cf4f2f9dd06763e/src/main/java/com/g4s8/ghman/web/TkGitHubAuthorization.java#L36-L38

The puzzle was created by Samih Omer on 08-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#42](https://github.com/g4s8/ghman/issues/42) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#42](https://github.com/g4s8/ghman/issues/42) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/933cf798-4467-4311-905d-d651ec171258); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@g4s8 what should we do with loggers? I think it's an ARC decision: should we use slf4j and pass `Logger` objects to constructor of classes? Something else?

**Comment by victornoel** [comment]
@0crat wait for ARC answer

**Comment by 0crat** [comment]
> @0crat wait for ARC answer ([here](https://github.com/g4s8/ghman/issues/42#issuecomment-508939536))

@victornoel The impediment for [#42](https://github.com/g4s8/ghman/issues/42) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@victornoel I think we can use something like logging decorators with single `Logger` slf4j dependency,
e.g.:
```java
class VerboseUser implements User {
  private final User users;
  private final Logger log;
  
  public void authorize(String token) {
    this.users.authorize(token);
    log.info("User %d (%s) authorized by token", this.uid(), urn)
  }
}
```

What do you think?

**Comment by victornoel** [comment]
@g4s8 ok for using decorator when needed, and what about instantiating those loggers? Should they be instantiated by class? by object? by the main? by the object creator? with which name?

**Comment by victornoel** [comment]
@g4s8 can I get more details on the question above?

**Comment by g4s8** [comment]
@victornoel I'd instantiate it in package private primary constructor to be able to inject fake logger for tests if needed, but to not allow foreign classes to provide invalid logger.

**Comment by victornoel** [comment]
@0crat wait for #80 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #80 to be merged ([here](https://github.com/g4s8/ghman/issues/42#issuecomment-515746475))

@victornoel Job [#42](https://github.com/g4s8/ghman/issues/42) is already on hold

**Comment by 0pdd** [comment]
The puzzle `4-c1ef585e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@3d7cf28e-ac85-4cc8-9914-f8c626ab1945, thread: pool-20-thread-7
org.xembly.Xembler[132] java.lang.IllegalArgumentException: failed to apply to DOM quietly: XPATH "/agenda/order[@job=&apos;gh:g4s8/ghman#42&apos;]";STRICT "1";ADDIF "inspector";
3:SET "ammaratef45";
org.xembly.Xembler[158] org.xembly.ImpossibleModificationException: directive #2: STRICT "1"
org.xembly.StrictDirective[72] org.xembly.ImpossibleModificationException: no current nodes while 1 expected
```

[0.49.0](https://github.com/zerocracy/farm): CID: [c6e860fc-59f8-4318-a99d-43d261892701](https://www.0crat.com/footprint/CJT4R32Q3/c6e860fc-59f8-4318-a99d-43d261892701), Type: "Start QA review"

**Comment by 0crat** [comment]
The job [#42](https://github.com/g4s8/ghman/issues/42) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
