### ISSUE TITLE
TkGitHubAuthorization.java:39-40: Implement unit tests...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#43]
The puzzle `4-6f9220be` from #4 has to be resolved: 

https://github.com/g4s8/ghman/blob/2198cd8faa8fac8cd00a046d4cf4f2f9dd06763e/src/main/java/com/g4s8/ghman/web/TkGitHubAuthorization.java#L39-L40

The puzzle was created by Samih Omer on 16-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#43](https://github.com/g4s8/ghman/issues/43) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#43](https://github.com/g4s8/ghman/issues/43) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/0309aa15-8872-4f30-b2fb-6978b4ac0476); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@0crat wait for #59 review/merge

**Comment by 0crat** [comment]
> @0crat wait for #59 review/merge ([here](https://github.com/g4s8/ghman/issues/43#issuecomment-508913355))

@olenagerasimova The impediment for [#43](https://github.com/g4s8/ghman/issues/43) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
The puzzle `4-6f9220be` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#75](https://github.com/g4s8/ghman/issues/75) is still not solved.

**Comment by 0crat** [comment]
The job [#43](https://github.com/g4s8/ghman/issues/43) is now out of scope

**Comment by 0crat** [comment]
Job [#43](https://github.com/g4s8/ghman/issues/43) is not in the agenda of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), can't inspect

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
