### ISSUE TITLE
Telegram takes depend on db source

### ISSUE THREAD

**Issue by olenagerasimova** [g4s8/ghman#45]
`TkNotifications` and `TkThread` depend on database source now, I believe that's completely wrong. These classes should have `Users` field instead of `DataSource` to keep low abstraction coupling and make unit testing possible and easy (we simply create `Users.Fake` implementation and will be happy). 
UPD We also got rid of datasource dependency in `BotApp.java`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#45](https://github.com/g4s8/ghman/issues/45) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
The job [#45](https://github.com/g4s8/ghman/issues/45) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/bfabf75f-f0d9-48c7-a1c7-3f32bb2c4528); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat waiting for PR #48

**Comment by 0crat** [comment]
> @0crat waiting for PR #48  ([here](https://github.com/g4s8/ghman/issues/45#issuecomment-504088584))

@scristalli The impediment for [#45](https://github.com/g4s8/ghman/issues/45) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by scristalli** [comment]
@olenagerasimova PR #48 has been merged. Could you please edit the task description to include the additional changes discussed and made in the PR? Then I think that we can close this.

**Comment by olenagerasimova** [comment]
@scristalli thanks

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#45](https://github.com/g4s8/ghman/issues/45) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)
