### ISSUE TITLE
TkApp.java:58-60: Refactor environment usage like...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#5]
The puzzle `1-41b37148` from #1 has to be resolved: 

https://github.com/g4s8/ghman/blob/a8f587ea02446832a0de164a20b03d7667218015/src/main/java/com/g4s8/ghman/web/TkApp.java#L58-L60

The puzzle was created by @g4s8 on 22-May-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#5](https://github.com/g4s8/ghman/issues/5) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#5](https://github.com/g4s8/ghman/issues/5); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#5](https://github.com/g4s8/ghman/issues/5) assigned to @samihibrahim[/z](https://www.0crat.com/u/samihibrahim), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/64021d25-54b4-42d0-bd33-d7d0331542c2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@samihibrahim[/z](https://www.0crat.com/u/samihibrahim) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by samihibrahim** [comment]
@0crat wait pull request #23 approval

**Comment by 0crat** [comment]
> @0crat wait pull request #23 approval ([here](https://github.com/g4s8/ghman/issues/5#issuecomment-500228590))

@samihibrahim The impediment for [#5](https://github.com/g4s8/ghman/issues/5) was registered successfully by @samihibrahim[/z](https://www.0crat.com/u/samihibrahim)

**Comment by 0pdd** [comment]
The puzzle `1-41b37148` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @samihibrahim[/z](https://www.0crat.com/u/samihibrahim), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ammaratef45** [comment]
@samihibrahim One of your commits doesn't mention the issue,

please confirm you will try to avoid that next time.

**Comment by 0crat** [comment]
The job [#5](https://github.com/g4s8/ghman/issues/5) is now out of scope

**Comment by samihibrahim** [comment]
Confirmed & sorry.

**Comment by ammaratef45** [comment]
@samihibrahim no problem
Also, don't forget to mention the person you are replying to ([here](https://github.com/g4s8/ghman/issues/5#issuecomment-501191041) you should mention me)

**Comment by samihibrahim** [comment]
@ammaratef45 Thanks for the tips :D

**Comment by ammaratef45** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @samihibrahim[/z](https://www.0crat.com/u/samihibrahim)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
