### ISSUE TITLE
TkCloseIssue.java:35-39: 1) find a way to avoid using...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#55]
The puzzle `11-b8952b84` from #11 has to be resolved: 

https://github.com/g4s8/ghman/blob/6ddde953d553b9a03a2e8d8f3cb86404c6e94165/src/main/java/com/g4s8/ghman/bot/TkCloseIssue.java#L35-L39

The puzzle was created by rultor on 26-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#55](https://github.com/g4s8/ghman/issues/55) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#55](https://github.com/g4s8/ghman/issues/55) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/4ad8c2da-3bde-4429-8d66-d3984769c10f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat wait for #85

**Comment by 0crat** [comment]
> @0crat wait for #85  ([here](https://github.com/g4s8/ghman/issues/55#issuecomment-522249561))

@scristalli The impediment for [#55](https://github.com/g4s8/ghman/issues/55) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0pdd** [comment]
The puzzle `11-b8952b84` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#55](https://github.com/g4s8/ghman/issues/55) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)
