### ISSUE TITLE
Provide clear guidelines about rebasing in PRs

### ISSUE THREAD

**Issue by victornoel** [g4s8/ghman#65]
Following some discussions:
- https://github.com/g4s8/ghman/pull/59#issuecomment-511106972
- https://t.me/zerocracy/7175

I think ARC should provide clear guidelines about rebasing versus adding commits fixing REV comments. Same about rebasing vs merging w.r.t. master.

Until now I was more for rebasing all the time, but I kind of had my mind changed (not 100%) so I would like to have a clear guideline so as not to think anymore about it :)

/cc @olenagerasimova @g4s8 @scristalli

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 I wasn't aware of it, but it seems that I am not the only one bothered by this kind of questions: https://github.com/zerocracy/zerocracy.github.io/pull/103#issuecomment-509644947

**Comment by 0crat** [comment]
The job [#65](https://github.com/g4s8/ghman/issues/65) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/a75ce87a-c7b2-4fd6-8c2f-10a1d36dcf1e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#65](https://github.com/g4s8/ghman/issues/65) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
