### ISSUE TITLE
Funding isn't configured for GitHub sponsor program

### ISSUE THREAD

**Issue by ammaratef45** [g4s8/ghman#69]
If you're opening the repo page in GitHub,
When clicking on the sponsor button on top of the page, you'll see the following
![Screenshot from 2019-07-15 11-56-15](https://user-images.githubusercontent.com/13663221/61208415-a791e480-a6f7-11e9-9b4c-952f00433ab1.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@ammaratef45 thanks, fixed, please check

**Comment by ammaratef45** [comment]
@g4s8 Great :+1:

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#69` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
