### ISSUE TITLE
Users.java:36-37: Extract interfaces and implement unit...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#7]
The puzzle `1-134b4230` from #1 has to be resolved: 

https://github.com/g4s8/ghman/blob/a8f587ea02446832a0de164a20b03d7667218015/src/main/java/com/g4s8/ghman/user/Users.java#L36-L37

The puzzle was created by @g4s8 on 22-May-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#7](https://github.com/g4s8/ghman/issues/7) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#7](https://github.com/g4s8/ghman/issues/7); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#7](https://github.com/g4s8/ghman/issues/7) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/0007f3e7-d926-47f2-93d8-3989927ca31e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 why issues in this repo are not assigned to me (or anyone) in github while I have them in my agenda?

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/g4s8/ghman/issues/7#issuecomment-499008049))

@g4s8 This is what I know about this job in [CJT4R32Q3](https://www.0crat.com/p/CJT4R32Q3), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#7](https://github.com/g4s8/ghman/issues/7) is [in scope](http://www.zerocracy.com/policy.html#14) for 6days
  * The role is `DEV`
  * The job is assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CJT4R32Q3?q=%7Bjob%3A%27gh%3Ag4s8%2Fghman%237%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@olenagerasimova I also can't modify it, it seems that only collaborators with write access (because there are no collaborators with read access for public repos) can be listed in `assignees` Github field.

**Comment by olenagerasimova** [comment]
@g4s8 I see, thanks

**Comment by olenagerasimova** [comment]
@0crat wait for review/merge #15

**Comment by 0crat** [comment]
> @0crat wait for review/merge #15 ([here](https://github.com/g4s8/ghman/issues/7#issuecomment-499764609))

@olenagerasimova The impediment for [#7](https://github.com/g4s8/ghman/issues/7) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
The puzzle `1-134b4230` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20) are still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#7](https://github.com/g4s8/ghman/issues/7) is now out of scope

**Comment by ammaratef45** [comment]
@olenagerasimova 
All commit messages should have links to issues, one of your commits doesn't have a link to the issue

Please confirm that you are going to avoid that in the future

**Comment by olenagerasimova** [comment]
@ammaratef45 I confirm

**Comment by ammaratef45** [comment]
> @ammaratef45 I confirm

Thanks

**Comment by ammaratef45** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20), [#53](https://github.com/g4s8/ghman/issues/53) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#19](https://github.com/g4s8/ghman/issues/19), [#53](https://github.com/g4s8/ghman/issues/53) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#20](https://github.com/g4s8/ghman/issues/20).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#17](https://github.com/g4s8/ghman/issues/17), [#53](https://github.com/g4s8/ghman/issues/53) are still not solved; solved: [#18](https://github.com/g4s8/ghman/issues/18), [#19](https://github.com/g4s8/ghman/issues/19), [#20](https://github.com/g4s8/ghman/issues/20).
