### ISSUE TITLE
pom.xml:168-170: Configure qulice plugin and test...

### ISSUE THREAD

**Issue by 0pdd** [g4s8/ghman#8]
The puzzle `1-da473f23` from #1 has to be resolved: 

https://github.com/g4s8/ghman/blob/a8f587ea02446832a0de164a20b03d7667218015/pom.xml#L168-L170

The puzzle was created by @g4s8 on 22-May-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by victornoel** [comment]
@g4s8 is this for adding CI validation or just setting up qulice/coverage in pom.xml?

I was reviewing PRs with clearly formatting problems. I spot some of them but I'm pretty sure I'm not as good as qulice: merging should be forbidden if qulice doesn't pass.

**Comment by g4s8** [comment]
@victornoel I'm trying to fix it right now: CI is working for my branches but doesn't work for forks

**Comment by g4s8** [comment]
@victornoel it should be enabled now, I suppose it will be triggered with next commit in each PR

**Comment by victornoel** [comment]
@g4s8 yep, it seemed to have run on #15 for example :)
It would make sense to use the --batch-mode option to avoid lots of printing about dependencies download by the way :)

**Comment by 0crat** [comment]
Job [#8](https://github.com/g4s8/ghman/issues/8) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#8](https://github.com/g4s8/ghman/issues/8) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/cb482ee9-0e7c-46aa-addc-440a2bce2591); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@0crat wait for #27 to be reviewed/merged

**Comment by 0crat** [comment]
> @0crat wait for #27 to be reviewed/merged ([here](https://github.com/g4s8/ghman/issues/8#issuecomment-500825406))

@olenagerasimova The impediment for [#8](https://github.com/g4s8/ghman/issues/8) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
The puzzle `1-da473f23` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/g4s8/ghman/issues/44) is still not solved.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#8](https://github.com/g4s8/ghman/issues/8) is not in the agenda of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), can't inspect

**Comment by 0crat** [comment]
The job [#8](https://github.com/g4s8/ghman/issues/8) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)
