### ISSUE TITLE
Gitlint configuration is broken

### ISSUE THREAD

**Issue by victornoel** [g4s8/ghman#81]
See for example: https://circleci.com/gh/g4s8/ghman/188

The PR for this build has correct commit messages but there are some errors in the history that makes it fail.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, fixed in https://github.com/g4s8/ghman/commit/db1a6840a369b699cd49f081797c26632bb21a9b

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#81` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
