### ISSUE TITLE
Bot doesn't notify users on new notifications

### ISSUE THREAD

**Issue by g4s8** [g4s8/ghman#9]
Let's monitor new unread messages and notify user if found. Mark locally this message as read right after message.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#9](https://github.com/g4s8/ghman/issues/9); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#9](https://github.com/g4s8/ghman/issues/9) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/61b27286-e547-48e5-878c-5eb983bbbde0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 
> Let's monitor new unread messages and notify user if found

Do I understand correctly that message in this sentence = github notification from `threads` table? And we want to monitor this table for unread notifications and send them to telegram?

**Comment by g4s8** [comment]
@olenagerasimova yes, each thread may be updated by new message (notification) or new thread may be created for new notification

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@0crat wait please for review/merge of #26

**Comment by 0crat** [comment]
> @0crat wait please for review/merge of #26  ([here](https://github.com/g4s8/ghman/issues/9#issuecomment-500554357))

@olenagerasimova The impediment for [#9](https://github.com/g4s8/ghman/issues/9) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#29](https://github.com/g4s8/ghman/issues/29), [#30](https://github.com/g4s8/ghman/issues/30), [#31](https://github.com/g4s8/ghman/issues/31) are still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 could you close this, please? #26 was merged

**Comment by g4s8** [comment]
@olenagerasimova thanks

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#9](https://github.com/g4s8/ghman/issues/9) is now out of scope

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#30](https://github.com/g4s8/ghman/issues/30), [#31](https://github.com/g4s8/ghman/issues/31), [#73](https://github.com/g4s8/ghman/issues/73) are still not solved; solved: [#29](https://github.com/g4s8/ghman/issues/29).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#30](https://github.com/g4s8/ghman/issues/30), [#73](https://github.com/g4s8/ghman/issues/73) are still not solved; solved: [#29](https://github.com/g4s8/ghman/issues/29), [#31](https://github.com/g4s8/ghman/issues/31).
